# Generated by Django 3.2 on 2023-12-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_id',
        ),
    ]
